{% set name = "playwright" %}
{% set version = "1.62.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/microsoft/{{ name }}/archive//v{{ version }}.tar.gz
  sha256: b778e484d6ec5c93a2ac8872f1c353e80aff9e5f7103d6b3b51b85dfd9ba56b2

build:
  number: 0

requirements:
  build:
    - nodejs >=20
  host:
    - nodejs >=20
  run:
    - nodejs >=20

test:
  commands:
    - npm list -g playwright
    - playwright --version

about:
  home: https://playwright.dev
  summary: 'Playwright is a framework for Web Testing and Automation. It allows testing Chromium, Firefox and WebKit with a single API.'
  description: |
    Playwright is a framework for Web Testing and Automation. It allows
    testing Chromium, Firefox and WebKit with a single API.
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  doc_url: https://playwright.dev/docs/intro
  dev_url: https://github.com/microsoft/playwright

extra:
  recipe-maintainers:
    - jan-janssen
  skip-lints:
    - host_section_needs_exact_pinnings
