{% set name = "playwright" %}
{% set version = "1.50.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/microsoft/{{ name }}/archive//v{{ version }}.tar.gz
  sha256: caa342a409d230eb86828291e8e1bb6208e08eb0b0cff65d2fa1d14d44c2988a

build:
  number: 0
  # nodejs is not avaliable on linux-s390x
  skip: True  # [s390x]

requirements:
  build:
    - nodejs
  host:
    - nodejs
  run:
    - nodejs

test:
  commands:
    - npm list -g playwright
    - npx playwright --version

about:
  home: https://playwright.dev
  summary: 'Playwright is a framework for Web Testing and Automation. It allows testing Chromium, Firefox and WebKit with a single API.'
  description: |
    Playwright is a framework for Web Testing and Automation. It allows
    testing Chromium, Firefox and WebKit with a single API.
  license: Apache-2.0
  license_file: LICENSE
  doc_url: https://playwright.dev/docs/
  dev_url: https://github.com/microsoft/playwright

extra:
  recipe-maintainers:
    - jan-janssen
