{% set name = "playwright" %}
{% set version = "1.45.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/microsoft/{{ name }}/archive//v{{ version }}.tar.gz
  sha256: 6618dc4a509eba178c0033351806780f056d4fadcbb7b9b4e51498e5da46afda

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - nodejs
  host:
    - yarn <2
    - nodejs
    - pnpm
    - pnpm-licenses
  run:
    - nodejs

test:
  commands:
    - npm list -g playwright
    - npx playwright --version

about:
  home: https://playwright.dev
  summary: 'Playwright is a framework for Web Testing and Automation. It allows testing Chromium, Firefox and WebKit with a single API.'
  description: |
    Playwright is a framework for Web Testing and Automation. It allows
    testing Chromium, Firefox and WebKit with a single API.
  license: Apache-2.0
  license_file: LICENSE
  doc_url: https://playwright.dev/docs/
  dev_url: https://github.com/microsoft/playwright

extra:
  recipe-maintainers:
    - jan-janssen
