{% set name = "playwright" %}
{% set version = "1.48.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/microsoft/{{ name }}/archive//v{{ version }}.tar.gz
  sha256: 0939b95acbc47e02d54da19185e7c019a44b7922d26a5779733661e3986e146c

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - nodejs
  host:
    - yarn <2
    - nodejs
    - pnpm
    - pnpm-licenses
  run:
    - nodejs

test:
  commands:
    - npm list -g playwright
    - npx playwright --version

about:
  home: https://playwright.dev
  summary: 'Playwright is a framework for Web Testing and Automation. It allows testing Chromium, Firefox and WebKit with a single API.'
  description: |
    Playwright is a framework for Web Testing and Automation. It allows
    testing Chromium, Firefox and WebKit with a single API.
  license: Apache-2.0
  license_file: LICENSE
  doc_url: https://playwright.dev/docs/
  dev_url: https://github.com/microsoft/playwright

extra:
  recipe-maintainers:
    - jan-janssen
